name: Test Installing Qt

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: "npm ci"
        run: npm ci

      - name: "npm run build"
        run: npm run build

      - name: Install Qt
        uses: ./
        with:
          modules: qtcharts qtwebengine

      - name: Build test project
        run: |
          cd tests/TestWithModules
          ls $Qt5_Dir/lib/cmake
          python3 -m aqt install -O yo 5.12.6 mac desktop -m qtcharts qtwebengine
          ls yo/5.12.6/clang_64/lib/cmake/
          qmake .
          make
          ls
        shell: bash

