name: Test Installing Qt

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: "npm ci"
        run: npm ci

      - name: "npm run build"
        run: npm run build

      - name: Install Qt
        uses: ./
        with:
          modules: qtcharts qtwebengine

      - name: run on mac
        if: startsWith(matrix.os, 'windows')
        run: echo "::add-path::%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\16.0.28625.61\bin\Hostx64\x64\"
        shell: bash
          
      - name: Build test project
        run: |
          cd tests/TestWithModules
          ls $Qt5_Dir/lib/cmake
          qmake .
          make
          ls
        shell: bash

