name: Test Installing Qt

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v1

      - name: "npm ci"
        run: npm ci

      - name: "npm run build"
        run: npm run build

      - name: "npm run test"
        run: npm run test
        
      - name: Install Qt
        uses: ./

      - name: Check for Qt installation
        run: |
          dir ${GITHUB_WORKSPACE}
          echo ${Qt5_DIR}
          echo ${PATH}